### ISSUE TITLE
Filter By Form Issue on 3.6

### ISSUE THREAD

**Issue by fpsampayo** [fpsampayo/qgis-navtable#5]
We have a problem with [this hack](https://github.com/fpuga/qgis-navtable/blob/master/src/NavTable/gui/NTSelectByFormDialog.py#L60).

On actual 3.4 works fine but in 3.6 the original QgsAttributeForm shows all the buttons without functionality. 

Find a solution to avoid this behavior. 

Maybe we could add this feature inside select by expression form.

Actual form on 3.6:
![image](https://user-images.githubusercontent.com/912161/53413774-39a98280-39cd-11e9-8ab7-7f6ef2b49110.png)

Expected:
![image](https://user-images.githubusercontent.com/912161/53413834-6cec1180-39cd-11e9-8529-2747c829047e.png)

**Comment by fpuga** [comment]
I think that [findChild](https://doc.qt.io/qt-5.12/qobject.html#findChild) or findChildren can be used to get the buttons. But i think that the form is not [setting a name](https://stackoverflow.com/questions/8983345/get-variable-name-of-qt-widget-for-use-in-stylesheet) for the buttons.

Maybe an issue can be raised against QgsAttributeForm to fill that names an make customization easy.
```
for c in form.findChildren(QPushButton):
    print(c.objectName()
```

By the way, i never, ever recommend [this kind of code construction](https://github.com/fpsampayo/qgis-navtable/blob/master/src/NavTable/gui/NTSelectByFormDialog.py#L68-L75):

```
try:
    foo = 1/0
except:
   pass
```

A very difficult to debug problems can arise using
* except instead of a more accurate exception type
* not logging the issue that is happening

**Comment by fpsampayo** [comment]
I resolve this. 

I hide the **searchButtonBox** and add new one with only two options (accept and reject). Accept has been connected to **searchZoomTo** method of **QgsAttributeForm** class.

The loop and except clauses has been discarted now.
